// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarControl.proto

package com.robotic.goldenridge.blecontroller;

public final class CarControlProtos {
  private CarControlProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CarControlOrBuilder extends
      // @@protoc_insertion_point(interface_extends:control.CarControl)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 steer = 1;</code>
     */
    boolean hasSteer();
    /**
     * <code>required int32 steer = 1;</code>
     */
    int getSteer();

    /**
     * <code>required int32 speed = 2;</code>
     */
    boolean hasSpeed();
    /**
     * <code>required int32 speed = 2;</code>
     */
    int getSpeed();

    /**
     * <code>optional int32 camHor = 3;</code>
     */
    boolean hasCamHor();
    /**
     * <code>optional int32 camHor = 3;</code>
     */
    int getCamHor();

    /**
     * <code>optional int32 camVer = 4;</code>
     */
    boolean hasCamVer();
    /**
     * <code>optional int32 camVer = 4;</code>
     */
    int getCamVer();

    /**
     * <code>optional bool HeadLight = 5;</code>
     */
    boolean hasHeadLight();
    /**
     * <code>optional bool HeadLight = 5;</code>
     */
    boolean getHeadLight();
  }
  /**
   * Protobuf type {@code control.CarControl}
   */
  public static final class CarControl extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:control.CarControl)
      CarControlOrBuilder {
    // Use CarControl.newBuilder() to construct.
    private CarControl(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CarControl(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CarControl defaultInstance;
    public static CarControl getDefaultInstance() {
      return defaultInstance;
    }

    public CarControl getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CarControl(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              steer_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              speed_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              camHor_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              camVer_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              headLight_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.robotic.goldenridge.blecontroller.CarControlProtos.internal_static_control_CarControl_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.robotic.goldenridge.blecontroller.CarControlProtos.internal_static_control_CarControl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl.class, com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl.Builder.class);
    }

    public static com.google.protobuf.Parser<CarControl> PARSER =
        new com.google.protobuf.AbstractParser<CarControl>() {
      public CarControl parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CarControl(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CarControl> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STEER_FIELD_NUMBER = 1;
    private int steer_;
    /**
     * <code>required int32 steer = 1;</code>
     */
    public boolean hasSteer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 steer = 1;</code>
     */
    public int getSteer() {
      return steer_;
    }

    public static final int SPEED_FIELD_NUMBER = 2;
    private int speed_;
    /**
     * <code>required int32 speed = 2;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 speed = 2;</code>
     */
    public int getSpeed() {
      return speed_;
    }

    public static final int CAMHOR_FIELD_NUMBER = 3;
    private int camHor_;
    /**
     * <code>optional int32 camHor = 3;</code>
     */
    public boolean hasCamHor() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 camHor = 3;</code>
     */
    public int getCamHor() {
      return camHor_;
    }

    public static final int CAMVER_FIELD_NUMBER = 4;
    private int camVer_;
    /**
     * <code>optional int32 camVer = 4;</code>
     */
    public boolean hasCamVer() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 camVer = 4;</code>
     */
    public int getCamVer() {
      return camVer_;
    }

    public static final int HEADLIGHT_FIELD_NUMBER = 5;
    private boolean headLight_;
    /**
     * <code>optional bool HeadLight = 5;</code>
     */
    public boolean hasHeadLight() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool HeadLight = 5;</code>
     */
    public boolean getHeadLight() {
      return headLight_;
    }

    private void initFields() {
      steer_ = 0;
      speed_ = 0;
      camHor_ = 0;
      camVer_ = 0;
      headLight_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSteer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, steer_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, speed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, camHor_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, camVer_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, headLight_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, steer_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, speed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, camHor_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, camVer_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, headLight_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code control.CarControl}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:control.CarControl)
        com.robotic.goldenridge.blecontroller.CarControlProtos.CarControlOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.robotic.goldenridge.blecontroller.CarControlProtos.internal_static_control_CarControl_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.robotic.goldenridge.blecontroller.CarControlProtos.internal_static_control_CarControl_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl.class, com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl.Builder.class);
      }

      // Construct using com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        steer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        camHor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        camVer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        headLight_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.robotic.goldenridge.blecontroller.CarControlProtos.internal_static_control_CarControl_descriptor;
      }

      public com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl getDefaultInstanceForType() {
        return com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl.getDefaultInstance();
      }

      public com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl build() {
        com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl buildPartial() {
        com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl result = new com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.steer_ = steer_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.camHor_ = camHor_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.camVer_ = camVer_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.headLight_ = headLight_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl) {
          return mergeFrom((com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl other) {
        if (other == com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl.getDefaultInstance()) return this;
        if (other.hasSteer()) {
          setSteer(other.getSteer());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasCamHor()) {
          setCamHor(other.getCamHor());
        }
        if (other.hasCamVer()) {
          setCamVer(other.getCamVer());
        }
        if (other.hasHeadLight()) {
          setHeadLight(other.getHeadLight());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSteer()) {
          
          return false;
        }
        if (!hasSpeed()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int steer_ ;
      /**
       * <code>required int32 steer = 1;</code>
       */
      public boolean hasSteer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 steer = 1;</code>
       */
      public int getSteer() {
        return steer_;
      }
      /**
       * <code>required int32 steer = 1;</code>
       */
      public Builder setSteer(int value) {
        bitField0_ |= 0x00000001;
        steer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 steer = 1;</code>
       */
      public Builder clearSteer() {
        bitField0_ = (bitField0_ & ~0x00000001);
        steer_ = 0;
        onChanged();
        return this;
      }

      private int speed_ ;
      /**
       * <code>required int32 speed = 2;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 speed = 2;</code>
       */
      public int getSpeed() {
        return speed_;
      }
      /**
       * <code>required int32 speed = 2;</code>
       */
      public Builder setSpeed(int value) {
        bitField0_ |= 0x00000002;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 speed = 2;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000002);
        speed_ = 0;
        onChanged();
        return this;
      }

      private int camHor_ ;
      /**
       * <code>optional int32 camHor = 3;</code>
       */
      public boolean hasCamHor() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 camHor = 3;</code>
       */
      public int getCamHor() {
        return camHor_;
      }
      /**
       * <code>optional int32 camHor = 3;</code>
       */
      public Builder setCamHor(int value) {
        bitField0_ |= 0x00000004;
        camHor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 camHor = 3;</code>
       */
      public Builder clearCamHor() {
        bitField0_ = (bitField0_ & ~0x00000004);
        camHor_ = 0;
        onChanged();
        return this;
      }

      private int camVer_ ;
      /**
       * <code>optional int32 camVer = 4;</code>
       */
      public boolean hasCamVer() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 camVer = 4;</code>
       */
      public int getCamVer() {
        return camVer_;
      }
      /**
       * <code>optional int32 camVer = 4;</code>
       */
      public Builder setCamVer(int value) {
        bitField0_ |= 0x00000008;
        camVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 camVer = 4;</code>
       */
      public Builder clearCamVer() {
        bitField0_ = (bitField0_ & ~0x00000008);
        camVer_ = 0;
        onChanged();
        return this;
      }

      private boolean headLight_ ;
      /**
       * <code>optional bool HeadLight = 5;</code>
       */
      public boolean hasHeadLight() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool HeadLight = 5;</code>
       */
      public boolean getHeadLight() {
        return headLight_;
      }
      /**
       * <code>optional bool HeadLight = 5;</code>
       */
      public Builder setHeadLight(boolean value) {
        bitField0_ |= 0x00000010;
        headLight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool HeadLight = 5;</code>
       */
      public Builder clearHeadLight() {
        bitField0_ = (bitField0_ & ~0x00000010);
        headLight_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:control.CarControl)
    }

    static {
      defaultInstance = new CarControl(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:control.CarControl)
  }

  public interface FeedBackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:control.FeedBack)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool Decode = 1;</code>
     */
    boolean hasDecode();
    /**
     * <code>required bool Decode = 1;</code>
     */
    boolean getDecode();

    /**
     * <code>optional int32 frontDist = 2;</code>
     */
    boolean hasFrontDist();
    /**
     * <code>optional int32 frontDist = 2;</code>
     */
    int getFrontDist();

    /**
     * <code>optional int32 rearDist = 3;</code>
     */
    boolean hasRearDist();
    /**
     * <code>optional int32 rearDist = 3;</code>
     */
    int getRearDist();
  }
  /**
   * Protobuf type {@code control.FeedBack}
   */
  public static final class FeedBack extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:control.FeedBack)
      FeedBackOrBuilder {
    // Use FeedBack.newBuilder() to construct.
    private FeedBack(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FeedBack(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FeedBack defaultInstance;
    public static FeedBack getDefaultInstance() {
      return defaultInstance;
    }

    public FeedBack getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FeedBack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              decode_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              frontDist_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rearDist_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.robotic.goldenridge.blecontroller.CarControlProtos.internal_static_control_FeedBack_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.robotic.goldenridge.blecontroller.CarControlProtos.internal_static_control_FeedBack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack.class, com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack.Builder.class);
    }

    public static com.google.protobuf.Parser<FeedBack> PARSER =
        new com.google.protobuf.AbstractParser<FeedBack>() {
      public FeedBack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeedBack(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<FeedBack> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DECODE_FIELD_NUMBER = 1;
    private boolean decode_;
    /**
     * <code>required bool Decode = 1;</code>
     */
    public boolean hasDecode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool Decode = 1;</code>
     */
    public boolean getDecode() {
      return decode_;
    }

    public static final int FRONTDIST_FIELD_NUMBER = 2;
    private int frontDist_;
    /**
     * <code>optional int32 frontDist = 2;</code>
     */
    public boolean hasFrontDist() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 frontDist = 2;</code>
     */
    public int getFrontDist() {
      return frontDist_;
    }

    public static final int REARDIST_FIELD_NUMBER = 3;
    private int rearDist_;
    /**
     * <code>optional int32 rearDist = 3;</code>
     */
    public boolean hasRearDist() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 rearDist = 3;</code>
     */
    public int getRearDist() {
      return rearDist_;
    }

    private void initFields() {
      decode_ = false;
      frontDist_ = 0;
      rearDist_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDecode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, decode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, frontDist_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, rearDist_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, decode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, frontDist_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, rearDist_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code control.FeedBack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:control.FeedBack)
        com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.robotic.goldenridge.blecontroller.CarControlProtos.internal_static_control_FeedBack_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.robotic.goldenridge.blecontroller.CarControlProtos.internal_static_control_FeedBack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack.class, com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack.Builder.class);
      }

      // Construct using com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        decode_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        frontDist_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        rearDist_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.robotic.goldenridge.blecontroller.CarControlProtos.internal_static_control_FeedBack_descriptor;
      }

      public com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack getDefaultInstanceForType() {
        return com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack.getDefaultInstance();
      }

      public com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack build() {
        com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack buildPartial() {
        com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack result = new com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.decode_ = decode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.frontDist_ = frontDist_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rearDist_ = rearDist_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack) {
          return mergeFrom((com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack other) {
        if (other == com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack.getDefaultInstance()) return this;
        if (other.hasDecode()) {
          setDecode(other.getDecode());
        }
        if (other.hasFrontDist()) {
          setFrontDist(other.getFrontDist());
        }
        if (other.hasRearDist()) {
          setRearDist(other.getRearDist());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDecode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.robotic.goldenridge.blecontroller.CarControlProtos.FeedBack) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean decode_ ;
      /**
       * <code>required bool Decode = 1;</code>
       */
      public boolean hasDecode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool Decode = 1;</code>
       */
      public boolean getDecode() {
        return decode_;
      }
      /**
       * <code>required bool Decode = 1;</code>
       */
      public Builder setDecode(boolean value) {
        bitField0_ |= 0x00000001;
        decode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool Decode = 1;</code>
       */
      public Builder clearDecode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        decode_ = false;
        onChanged();
        return this;
      }

      private int frontDist_ ;
      /**
       * <code>optional int32 frontDist = 2;</code>
       */
      public boolean hasFrontDist() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 frontDist = 2;</code>
       */
      public int getFrontDist() {
        return frontDist_;
      }
      /**
       * <code>optional int32 frontDist = 2;</code>
       */
      public Builder setFrontDist(int value) {
        bitField0_ |= 0x00000002;
        frontDist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 frontDist = 2;</code>
       */
      public Builder clearFrontDist() {
        bitField0_ = (bitField0_ & ~0x00000002);
        frontDist_ = 0;
        onChanged();
        return this;
      }

      private int rearDist_ ;
      /**
       * <code>optional int32 rearDist = 3;</code>
       */
      public boolean hasRearDist() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 rearDist = 3;</code>
       */
      public int getRearDist() {
        return rearDist_;
      }
      /**
       * <code>optional int32 rearDist = 3;</code>
       */
      public Builder setRearDist(int value) {
        bitField0_ |= 0x00000004;
        rearDist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rearDist = 3;</code>
       */
      public Builder clearRearDist() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rearDist_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:control.FeedBack)
    }

    static {
      defaultInstance = new FeedBack(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:control.FeedBack)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_control_CarControl_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_control_CarControl_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_control_FeedBack_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_control_FeedBack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020CarControl.proto\022\007control\"]\n\nCarContro" +
      "l\022\r\n\005steer\030\001 \002(\005\022\r\n\005speed\030\002 \002(\005\022\016\n\006camHo" +
      "r\030\003 \001(\005\022\016\n\006camVer\030\004 \001(\005\022\021\n\tHeadLight\030\005 \001" +
      "(\010\"?\n\010FeedBack\022\016\n\006Decode\030\001 \002(\010\022\021\n\tfrontD" +
      "ist\030\002 \001(\005\022\020\n\010rearDist\030\003 \001(\005B6\n\"com.robot" +
      "ic.goldenridge.blecontrollerB\020CarControlPro" +
      "tos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_control_CarControl_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_control_CarControl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_control_CarControl_descriptor,
        new String[] { "Steer", "Speed", "CamHor", "CamVer", "HeadLight", });
    internal_static_control_FeedBack_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_control_FeedBack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_control_FeedBack_descriptor,
        new String[] { "Decode", "FrontDist", "RearDist", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
