// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarControl.proto

package com.robotic.goldenridge.blecontroller;

public final class CarControlProtos {
  private CarControlProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CarControlOrBuilder extends
      // @@protoc_insertion_point(interface_extends:control.CarControl)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 steer = 1;</code>
     */
    boolean hasSteer();
    /**
     * <code>required int32 steer = 1;</code>
     */
    int getSteer();

    /**
     * <code>required int32 speed = 2;</code>
     */
    boolean hasSpeed();
    /**
     * <code>required int32 speed = 2;</code>
     */
    int getSpeed();
  }
  /**
   * Protobuf type {@code control.CarControl}
   */
  public static final class CarControl extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:control.CarControl)
      CarControlOrBuilder {
    // Use CarControl.newBuilder() to construct.
    private CarControl(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CarControl(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CarControl defaultInstance;
    public static CarControl getDefaultInstance() {
      return defaultInstance;
    }

    public CarControl getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CarControl(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              steer_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              speed_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.robotic.goldenridge.blecontroller.CarControlProtos.internal_static_control_CarControl_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.robotic.goldenridge.blecontroller.CarControlProtos.internal_static_control_CarControl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl.class, com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl.Builder.class);
    }

    public static com.google.protobuf.Parser<CarControl> PARSER =
        new com.google.protobuf.AbstractParser<CarControl>() {
      public CarControl parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CarControl(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CarControl> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STEER_FIELD_NUMBER = 1;
    private int steer_;
    /**
     * <code>required int32 steer = 1;</code>
     */
    public boolean hasSteer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 steer = 1;</code>
     */
    public int getSteer() {
      return steer_;
    }

    public static final int SPEED_FIELD_NUMBER = 2;
    private int speed_;
    /**
     * <code>required int32 speed = 2;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 speed = 2;</code>
     */
    public int getSpeed() {
      return speed_;
    }

    private void initFields() {
      steer_ = 0;
      speed_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSteer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, steer_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, speed_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, steer_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, speed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code control.CarControl}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:control.CarControl)
        com.robotic.goldenridge.blecontroller.CarControlProtos.CarControlOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.robotic.goldenridge.blecontroller.CarControlProtos.internal_static_control_CarControl_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.robotic.goldenridge.blecontroller.CarControlProtos.internal_static_control_CarControl_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl.class, com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl.Builder.class);
      }

      // Construct using com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        steer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.robotic.goldenridge.blecontroller.CarControlProtos.internal_static_control_CarControl_descriptor;
      }

      public com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl getDefaultInstanceForType() {
        return com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl.getDefaultInstance();
      }

      public com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl build() {
        com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl buildPartial() {
        com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl result = new com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.steer_ = steer_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.speed_ = speed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl) {
          return mergeFrom((com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl other) {
        if (other == com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl.getDefaultInstance()) return this;
        if (other.hasSteer()) {
          setSteer(other.getSteer());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSteer()) {
          
          return false;
        }
        if (!hasSpeed()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.robotic.goldenridge.blecontroller.CarControlProtos.CarControl) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int steer_ ;
      /**
       * <code>required int32 steer = 1;</code>
       */
      public boolean hasSteer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 steer = 1;</code>
       */
      public int getSteer() {
        return steer_;
      }
      /**
       * <code>required int32 steer = 1;</code>
       */
      public Builder setSteer(int value) {
        bitField0_ |= 0x00000001;
        steer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 steer = 1;</code>
       */
      public Builder clearSteer() {
        bitField0_ = (bitField0_ & ~0x00000001);
        steer_ = 0;
        onChanged();
        return this;
      }

      private int speed_ ;
      /**
       * <code>required int32 speed = 2;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 speed = 2;</code>
       */
      public int getSpeed() {
        return speed_;
      }
      /**
       * <code>required int32 speed = 2;</code>
       */
      public Builder setSpeed(int value) {
        bitField0_ |= 0x00000002;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 speed = 2;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000002);
        speed_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:control.CarControl)
    }

    static {
      defaultInstance = new CarControl(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:control.CarControl)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_control_CarControl_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_control_CarControl_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020CarControl.proto\022\007control\"*\n\nCarContro" +
      "l\022\r\n\005steer\030\001 \002(\005\022\r\n\005speed\030\002 \002(\005B6\n\"com.r" +
      "obotic.goldenridge.carControlB\020CarContro" +
      "lProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_control_CarControl_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_control_CarControl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_control_CarControl_descriptor,
        new String[] { "Steer", "Speed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
